# Step 1: Use a Red Hat UBI 8 base image
FROM registry.access.redhat.com/ubi8/ubi:latest

# Step 2: Update the system and install Apache
RUN yum update -y && yum install -y httpd
    

# Step 3: Set the working directory
WORKDIR /var/www/html

# Step 4: Copy the index.html file to the document root
COPY index.html /var/www/html/

# Step 5: Expose port 80
EXPOSE 80

# Step 6: Set the entrypoint to run Apache in the foreground
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]

# docker build -t samir3112/c-apache:v1 .
# docker run -d -p 80:80 samir3112/c-apache:v1